name: Small Fix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "event.from_id"
          replace: "event.sender_id"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Fix for from_id'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: xditya
          commit_user_email: 58950863+xditya@users.noreply.github.com
          commit_author: xditya <58950863+xditya@users.noreply.github.com>
